#Spring Configuration
spring:
  application:
    name: servicio.test
  cloud:
    config:
      enabled: true
#HTTP Server
server:
  port: 8081
# Discovery server Access
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
