server:  
  port: 8887
spring:
  application:
    name: config-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      

management:
  endpoints:
    web:
      exposure:
        include: '*'


logging:
  level:
   org.springframework.cloud: DEBUG
    
global-message: ♖ ♘ ♗ ♕ ♔ ♗ ♘ ♖ ♙ ♙ ♙ ♙ ♙ ♙ ♙ ♙ El servidor de configuración funcionando correctamente ♟ ♟ ♟ ♟ ♟ ♟ ♟ ♟ ♜ ♞ ♝ ♛ ♚ ♝ ♞ ♜

