server:
  port: 9090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
       # Ruta para el servicio de producto
        - id: producto
          uri: lb://producto
          predicates:
            - Path=/api/v0/productos/**
         # Ruta para el servicio de producto
        - id: carro
          uri: lb://carro
          predicates:
            - Path=/api/v0/carrito/**
         
        # Ruta para el servicio de autorización
        - id: auth-service
          uri: lb://autorizacion
          predicates:
            - Path=/api/v0/auth/**
        

