server:
  port: 9090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: producto
          uri: lb://PRODUCTO
          predicates:
            - Path=/api/v0/productos/**
        
        # Ruta para el servicio de autorización
        - id: auth-service
          uri: lb://autorizacion
          predicates:
            - Path=/api/v0/auth/**
        
        # Ruta específica para signin
        - id: auth-signin
          uri: lb://autorizacion
          predicates:
            - Path=/api/v0/auth/signin
        
        # Ruta específica para signup
        - id: auth-signup
          uri: lb://autorizacion
          predicates:
            - Path=/api/v0/auth/signup
