#Spring Configuration
spring:
  application:
    name: servicio.gatewau
#HTTP Server
server:
  port: 8080
# Discovery server Access
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
 cloud:
  gateway:
   discovery:
    localtor: 
     enable: true
    routes:
     - id:
      uri: lb://product-application
      predicates: 
       - Path=/api/v0/productos
