#Spring Configuration
spring:
  application:
    name: servicio.producto
  cloud:
    config:
      enabled: false
#HTTP Server
server:
  port: 9093
# Discovery server Access
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      

